# Generated by Django 4.1.1 on 2022-11-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TimeFrame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_started", models.DateField(blank=True, null=True)),
                ("date_finished", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
