# Generated by Django 4.1 on 2022-10-31 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("institution", models.CharField(blank=True, max_length=100)),
                ("date_finished", models.DateField(blank=True)),
            ],
        ),
    ]
