# Generated by Django 4.1.1 on 2022-11-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificate", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="date_finished",
            field=models.DateField(blank=True, null=True),
        ),
    ]
