# Generated by Django 4.1 on 2022-10-31 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("skill", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User_project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("date_started", models.DateField(blank=True)),
                ("date_finished", models.DateField(blank=True)),
                ("description", models.CharField(blank=True, max_length=1000)),
                ("position", models.CharField(blank=True, max_length=100)),
                ("external_link", models.URLField(blank=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "tools",
                    models.ManyToManyField(
                        blank=True, related_name="tools", to="skill.skill"
                    ),
                ),
            ],
        ),
    ]
