# Generated by Django 4.1.1 on 2022-11-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_project", "0003_alter_userproject_date_finished_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userproject",
            name="test",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
