# Generated by Django 4.1.1 on 2022-11-01 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("consultant", "0006_remove_consultant_projects_consultant_unavailable"),
        ("timeframe", "0001_initial"),
        ("user_project", "0004_userproject_test"),
    ]

    operations = [
        migrations.RemoveField(model_name="userproject", name="date_finished",),
        migrations.RemoveField(model_name="userproject", name="date_started",),
        migrations.RemoveField(model_name="userproject", name="position",),
        migrations.RemoveField(model_name="userproject", name="test",),
        migrations.AddField(
            model_name="userproject",
            name="assignee",
            field=models.ManyToManyField(
                blank=True, related_name="assignee", to="consultant.consultant"
            ),
        ),
        migrations.AddField(
            model_name="userproject",
            name="time_frame",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="timeframe.timeframe",
            ),
        ),
    ]
