# Generated by Django 4.1.1 on 2022-11-10 10:39

from django.db import migrations, models
import user_project.models


class Migration(migrations.Migration):

    dependencies = [
        ("user_project", "0005_remove_userproject_date_finished_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userproject",
            name="external_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userproject",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=user_project.models.UserProject.upload_to,
            ),
        ),
    ]
