# Generated by Django 4.1.1 on 2022-11-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultant", "0002_alter_consultant_addition_skills_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultant",
            name="profile_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="consultant",
            name="profile_slug_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
