# Generated by Django 4.1.1 on 2022-11-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultant", "0003_alter_consultant_profile_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultant",
            name="linked_in_link",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="consultant", name="summary", field=models.TextField(null=True),
        ),
    ]
