# Generated by Django 4.1.1 on 2022-11-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultant", "0004_alter_consultant_linked_in_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultant",
            name="linked_in_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
