# Generated by Django 4.1.1 on 2022-11-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timeframe", "0001_initial"),
        ("consultant", "0005_alter_consultant_linked_in_link"),
    ]

    operations = [
        migrations.RemoveField(model_name="consultant", name="projects",),
        migrations.AddField(
            model_name="consultant",
            name="unavailable",
            field=models.ManyToManyField(
                blank=True, related_name="unavailable", to="timeframe.timeframe"
            ),
        ),
    ]
