# Generated by Django 4.1.1 on 2022-11-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0006_remove_consultant_projects_consultant_unavailable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='image_path',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
