# Generated by Django 4.1.1 on 2022-11-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultant", "0009_alter_consultant_addition_skills_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultant",
            name="display_name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
