# Generated by Django 4.1.1 on 2022-11-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_alter_certificate_date_finished'),
        ('addition_skill', '0001_initial'),
        ('timeframe', '0001_initial'),
        ('skill', '0001_initial'),
        ('education', '0002_alter_education_date_finished'),
        ('language', '0001_initial'),
        ('consultant', '0011_alter_consultant_addition_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='addition_skills',
            field=models.ManyToManyField(blank=True, default='', related_name='addition_skills', to='addition_skill.addition_skill'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='certificates',
            field=models.ManyToManyField(blank=True, default='', related_name='certificates', to='certificate.certificate'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='edited_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='educations',
            field=models.ManyToManyField(blank=True, default='', related_name='educations', to='education.education'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='language_skills',
            field=models.ManyToManyField(blank=True, default='', related_name='language_skills', to='language.language'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='managed_certificates',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='managed_skills',
            field=models.ManyToManyField(blank=True, default='', related_name='managed_skills', to='skill.skill'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='manager_display_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='manager_on_premises_user_principal_name',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='primary_language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='role_category',
            field=models.CharField(choices=[('frontend', 'Frontend Developer'), ('backend', 'Backend Developer'), ('devops', 'DevOps Developer'), ('fullstack', 'Fullstack Developer')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='unavailable',
            field=models.ManyToManyField(blank=True, default='', related_name='unavailable', to='timeframe.timeframe'),
        ),
    ]
